#============================================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Use Releases file to packaging
# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
#============================================================================================================

name: Kernel by ower scripts

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Get OpenWrt firmware
      id: build
      if: (!cancelled())
      run: |
        [ -d openwrt-armvirt ] || mkdir -p openwrt-armvirt
        # curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_armvirt_.*/openwrt-armsr-armv8-.*\.tar.gz" | head -n 1 > DOWNLOAD_ARMVIRT
        # curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_armvirt_.*/openwrt-armvirt-.*\.tar.gz" | head -n 1 > DOWNLOAD_ARMVIRT
        curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_armvirt_.*/openwrt-armsr-armv8-.*\.tar.gz" | head -n 1 > DOWNLOAD_ARMVIRT
        # curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_armvirt_.*/immortalwrt-.*\.tar.gz" | head -n 1 > DOWNLOAD_ARMVIRT
        [ -s DOWNLOAD_ARMVIRT ] && wget -q -P openwrt-armvirt https://github.com/${GITHUB_REPOSITORY}/releases/download/$(cat DOWNLOAD_ARMVIRT)
        echo "build_tag=openwrt_image_v8_$(date +"%Y-%m-%d-%H-%M")" >> $GITHUB_OUTPUT

   # - name: Package Armvirt as OpenWrt
   #   uses: tsingui/openwrt_packit@master
   #   env:
   #     WHOAMI: tsingui
   #     OPENWRT_ARMVIRT: openwrt-armvirt/*.tar.gz
   #     PACKAGE_SOC: s905d_s905x3_s922x
        # KERNEL_AUTO_LATEST: false
   #     KERNEL_REPO_URL: https://github.com/tsingui/kernel/releases/tag/kernel_stable
        # KERNEL_REPO_URL: https://github.com/breakings/OpenWrt/releases/tag/kernel_stable
        # KERNEL_REPO_URL: https://github.com/ophub/kernel/releases/tag/kernel_stable
        # KERNEL_REPO_URL: https://github.com/ophub/kernel/releases/tag/kernel_flippy
   #     KERNEL_VERSION_NAME: 6.1.140_6.6.100_6.12.40
      - name: Packaging OpenWrt
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: openwrt-armvirt/*.tar.gz
          openwrt_board: s922x-ct2000
          openwrt_kernel: 6.1.y_6.6.y
          auto_kernel: true
          kernel_repo: tsingui/kernel
          kernel_usage: stable
          builder_name: tsingui

    - name: Upload OpenWrt Firmware to Release
      uses: ncipollo/release-action@v1
      with:
        # tag: openwrt_armvirt_v8_${{ env.PACKAGED_OUTPUTDATE }}
        tag: ${{ steps.build.outputs.build_tag }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ### **适用于Amlogic平台OpenWrt固件**
          * **固件信息：**
          默认IP: `10.0.0.2`
          默认用户名: `root`
          默认密码: `password/空`
